# GeckoPIDGrabber (c) Shadow Doggo.

import os
import json
import time
from datetime import datetime

class Logger:
    def __init__(self):
        self.date = datetime.now()
        self.regions = json.loads(open("regions.json").read())
        self.align = 0
        self.region = 0
        self.team = 0
        self.gender = 0
        self.eye_color = 0
        self.shoes = 0
        self.clothes = 0
        self.headgear = 0
        self.rank = 0
        self.weapon = 0
        self.sub_weapon = 0
        self.special_weapon = 0

    def create_log(self):
        if not os.path.isdir(f"./logs/{self.date.strftime('%Y-%m-%d')}"):
            os.makedirs(f"./logs/{self.date.strftime('%Y-%m-%d')}")

        with open(
            f"./logs/{self.date.strftime('%Y-%m-%d')}/{self.date.strftime('%Y-%m-%d %H-%M-%S')} log.txt",
            "w", encoding="utf-8"
        ) as f:
            f.write(f"GeckoPIDGrabber log from {self.date.strftime('%Y-%m-%d %H:%M:%S')}\n")

    def new_match(self, gecko, auto_logging, session_ptr, count):
        if auto_logging:
            self.align = 2

            if session_ptr != 0:
                session_idx = int.from_bytes(gecko.readmem(session_ptr + 0xBD, 1), "big")
                session_id = int.from_bytes(gecko.readmem(session_ptr + session_idx + 0xCC, 4), "big")
            else:
                session_id = 0

            with open(
                f"./logs/{self.date.strftime('%Y-%m-%d')}/{self.date.strftime('%Y-%m-%d %H-%M-%S')} log.txt",
                "a", encoding="utf-8"
            ) as f:
                f.write(
                    f"\n[Match {count}]\n\n  Time: {datetime.now().strftime('%H:%M:%S')}\n"
                    f"{' ' * self.align}Session ID: {session_id:X} ({session_id})\n"
                )
        else:
            if session_ptr != 0:
                session_idx = int.from_bytes(gecko.readmem(session_ptr + 0xBD, 1), "big")
                session_id = int.from_bytes(gecko.readmem(session_ptr + session_idx + 0xCC, 4), "big")
            else:
                session_id = 0

            with open(
                f"./logs/{self.date.strftime('%Y-%m-%d')}/{self.date.strftime('%Y-%m-%d %H-%M-%S')} log.txt",
                "a", encoding="utf-8"
            ) as f:
                f.write(f"\nSession ID: {session_id:X} ({session_id})\n")

    def log(self, gecko, log_stats, player_num, player_data, player_pid, player_pnid, player_name):
        self.region = int.from_bytes(player_data[0x2C:0x30], "big")
        self.team = int.from_bytes(player_data[0x33:0x34], "big")
        self.gender = int.from_bytes(player_data[0x37:0x38], "big")
        skin_tone = int.from_bytes(player_data[0x3B:0x3C], "big")
        self.eye_color = int.from_bytes(player_data[0x3F:0x40], "big")
        self.shoes = int.from_bytes(player_data[0x54:0x58], "big")
        self.clothes = int.from_bytes(player_data[0x70:0x74], "big")
        self.headgear = int.from_bytes(player_data[0x8C:0x90], "big")
        level = int.from_bytes(player_data[0xAF:0xB0], "big", signed=True) + 1
        self.rank = int.from_bytes(player_data[0xB3:0xB4], "big", signed=True)
        self.weapon = int.from_bytes(player_data[0x46:0x48], "big")
        self.sub_weapon = int.from_bytes(player_data[0x4A:0x4C], "big")
        self.special_weapon = int.from_bytes(player_data[0x4D:0x50], "big")

        player_log = (
            f"\n{' ' * self.align}[Player {player_num}]\n\n"
            f"{' ' * (self.align + 2)}Name: {player_name}\n"
            f"{' ' * (self.align + 2)}PID: {player_pid:X} ({player_pid})\n"
            f"{' ' * (self.align + 2)}PNID: {player_pnid}\n"
            f"{' ' * (self.align + 2)}Country: {self.get_region()[1]} ({ self.get_region()[0]})\n"
            f"{' ' * (self.align + 2)}Region: { self.get_region()[2]} ({self.region})\n"
            f"{' ' * (self.align + 2)}Team: {self.get_team()} ({self.team})\n"
            f"{' ' * (self.align + 2)}Gender: {self.get_gender()} ({self.gender})\n"
            f"{' ' * (self.align + 2)}Skin tone: {skin_tone}\n"
            f"{' ' * (self.align + 2)}Eye color: {self.get_eye_color()} ({self.eye_color})\n"
            f"{' ' * (self.align + 2)}Shoes: {self.get_shoes()} ({self.shoes})\n"
            f"{' ' * (self.align + 2)}Clothes: {self.get_clothes()} ({self.clothes})\n"
            f"{' ' * (self.align + 2)}Headgear: {self.get_headgear()} ({self.headgear})\n"
            f"{' ' * (self.align + 2)}Level: {level}\n"
            f"{' ' * (self.align + 2)}Rank: {self.get_rank()} ({self.rank})\n"
            f"{' ' * (self.align + 2)}Weapon: {self.get_weapon()} ({self.weapon})\n"
            f"{' ' * (self.align + 2)}Sub weapon: {self.get_sub_weapon()} ({self.sub_weapon})\n"
            f"{' ' * (self.align + 2)}Special weapon: {self.get_special_weapon()} ({self.special_weapon})\n"
        )  # Long ass string.

        with open(
            f"./logs/{self.date.strftime('%Y-%m-%d')}/{self.date.strftime('%Y-%m-%d %H-%M-%S')} log.txt",
            "a", encoding="utf-8"
        ) as f:
            f.write(player_log)

        if log_stats:
            stats = gecko.readmem(0x107AF944, 288)

            if player_num == 1:  # Buffer player 1 data until stats are updated.
                while gecko.readmem(0x107AF944, 288) == stats:
                    time.sleep(10)

            winning_team = int.from_bytes(gecko.readmem(0x107AF917, 1), "big")
            print(winning_team)
            stats = gecko.readmem(0x107AF944, 288)  # Read the updated stats again.
            offset = (player_num - 1) * 0x20
            points = int.from_bytes(stats[offset + 0x3A:offset + 0x3C], "big")
            kills = int.from_bytes(stats[offset + 0x3E:offset + 0x40], "big")
            deaths = int.from_bytes(stats[offset + 0x42:offset + 0x44], "big")

            player_results = (
                f"    Points: {points}p\n"
                f"    Kills: {kills}\n"
                f"    Deaths: {deaths}\n"
                f"    Result: {"Win" if self.team == winning_team else "Lose"}\n"
            )

            with open(
                f"./logs/{self.date.strftime('%Y-%m-%d')}/{self.date.strftime('%Y-%m-%d %H-%M-%S')} log.txt",
                "a", encoding="utf-8"
            ) as f:
                f.write(player_results)

    def get_region(self):
        for i in self.regions:
            for j in range(len(i["regions"])):
                if i["regions"][j]["id"] == self.region:
                    return (
                        i["id"],
                        i["name"],
                        i["regions"][j]["name"]
                        .encode("utf-8", errors="ignore")
                        .decode("utf-8"),
                    )

        return "None", "None", "None"

    def get_team(self):
        match self.team:
            case 0: return "Alpha"
            case 1: return "Bravo"
            case _: return "Unknown"

    def get_gender(self):
        match self.gender:
            case 0: return "Girl"
            case 1: return "Boy"
            case 2: return "Octoling"
            case _: return "Unknown"

    def get_eye_color(self):
        match self.eye_color:
            case 0: return "Brown"
            case 1: return "Pink"
            case 2: return "Blue"
            case 3: return "Orange"
            case 4: return "Green"
            case 5: return "Black"
            case 6: return "Yellow"
            case _: return "Unknown"

    def get_shoes(self):
        match self.shoes:
            case 0: return "ありのまま"
            case 1: return "Cream Basics"
            case 1000: return "Blue Lo-Tops"
            case 1001: return "Banana Basics"
            case 1002: return "LE Lo-Tops"
            case 1003: return "White Seahorses"
            case 1004: return "Orange Lo-Tops"
            case 1005: return "Black Seahorses"
            case 1006: return "Clownfish Basics"
            case 1007: return "Yellow Seahorses"
            case 1008: return "Strapping Whites"
            case 1009: return "Strapping Reds"
            case 1010: return "Soccer Cleats"
            case 1011: return "LE Soccer Cleats"
            case 2000: return "Red Hi-Horses"
            case 2001: return "Zombie Hi-Horses"
            case 2002: return "Cream Hi-Tops"
            case 2003: return "Purple Hi-Horses"
            case 2004: return "Hunter Hi-Tops"
            case 2005: return "Red Hi-Tops"
            case 2006: return "Gold Hi-Horses"
            case 2007: return "SQUID GIRL Shoes"
            case 2008: return "Shark Mawcasins"
            case 2009: return "Mawcasins"
            case 3000: return "Pink Trainers"
            case 3001: return "Orange Arrows"
            case 3002: return "Neon Sea Slugs"
            case 3003: return "White Arrows"
            case 3004: return "Cyan Trainers"
            case 3005: return "Blue Sea Slugs"
            case 3006: return "Red Sea Slugs"
            case 3007: return "Purple Sea Slugs"
            case 3008: return "Crazy Arrows"
            case 3009: return "Black Trainers"
            case 4000: return "Oyster Clogs"
            case 4001: return "Choco Clogs"
            case 4002: return "Blueberry Casuals"
            case 4003: return "Plum Casuals"
            case 4006: return "Traditional Sandals"
            case 5000: return "Trail Boots"
            case 5001: return "Custom Trail Boots"
            case 5002: return "Pro Trail Boots"
            case 6000: return "Moto Boots"
            case 6001: return "Tan Work Boots"
            case 6002: return "Red Work Boots"
            case 6003: return "Blue Moto Boots"
            case 6004: return "Green Rain Boots"
            case 6005: return "Acerola Rain Boots"
            case 6006: return "Punk Whites"
            case 6007: return "Punk Cherries"
            case 6008: return "Punk Yellows"
            case 6009: return "Bubble Rain Boots"
            case 6010: return "Snowy Down Boots"
            case 6011: return "Icy Down Boots"
            case 7000: return "Blue Slip-Ons"
            case 7001: return "Red Slip-Ons"
            case 7002: return "Squid-Stitch Slip-Ons"
            case 8000: return "White Kicks"
            case 8001: return "Cherry Kicks"
            case 8002: return "Turquoise Kicks"
            case 8003: return "Squink Wingtips"
            case 8004: return "Roasted Brogues"
            case 25000: return "School Shoes"
            case 25001: return "Samurai Shoes"
            case 25002: return "Power Boots"
            case 27000: return "Hero Runner Replicas"
            case 27001: return "?MSN001"
            case 27002: return "?MSN002"
            case 27003: return "?MSN003"
            case 27004: return "Armor Boot Replicas"
            case 28000: return "Octoling Boots"
            case 29000: return "?Attack_Up"
            case 29001: return "?Defense_Up"
            case 29002: return "?MainInk_Save"
            case 29003: return "?SubInk_Save"
            case 29004: return "?Inkrecovery_Up"
            case 29005: return "?HumanMove_Up"
            case 29006: return "?SquidMove_Up"
            case 29007: return "?SpecialIncrease_Up"
            case 29008: return "?SpecialTime_Up"
            case 29009: return "?RespawnTime_Save"
            case 29010: return "?RespawnSpecialGauge_Save"
            case 29011: return "?JumpTime_Save"
            case 29012: return "?BombDistance_Up"
            case 29013: return "?TrapDetect"
            case 29014: return "?EnemyInkEffect_Reduction"
            case 29015: return "?SuperJumpSign_Hide"
            case 29500: return "?SUP000"
            case 29501: return "?SUP001"
            case _: return "Unknown"

    def get_clothes(self):
        match self.clothes:
            case 0: return "?NoClothes"
            case 1: return "Basic Tee"
            case 1000: return "White Tee"
            case 1001: return "Black Squideye"
            case 1003: return "Sky-Blue Squideye"
            case 1004: return "Rockenberg White"
            case 1005: return "Rockenberg Black"
            case 1006: return "Black Tee"
            case 1007: return "Sunny-Day Tee"
            case 1008: return "Rainy-Day Tee"
            case 1009: return "Reggae Tee"
            case 1010: return "Fugu Tee"
            case 1011: return "Mint Tee"
            case 1012: return "Grape Tee"
            case 1013: return "Red Vector Tee"
            case 1014: return "Gray Vector Tee"
            case 1015: return "Blue Peaks Tee"
            case 1016: return "Ivory Peaks Tee"
            case 1017: return "Squid-Stitch Tee"
            case 1018: return "Pirate-Stripe Tee"
            case 1019: return "Sailor-Stripe Tee"
            case 1020: return "White 8-Bit FishFry"
            case 1021: return "Black 8-Bit FishFry"
            case 1022: return "White Anchor Tee"
            case 1023: return "Black Anchor Tee"
            case 1024: return "White Line Tee"
            case 1025: return "Black Pipe Tee"
            case 1026: return "Carnivore Tee"
            case 1027: return "Pearl Tee"
            case 1028: return "Octo Tee"
            case 1029: return "Herbivore Tee"
            case 2000: return "White Striped LS"
            case 2001: return "Black LS"
            case 2002: return "Purple Camo LS"
            case 2003: return "Navy Striped LS"
            case 2004: return "Zekko Baseball LS"
            case 2005: return "Varsity Baseball LS"
            case 2006: return "Black Baseball LS"
            case 2007: return "White Baseball LS"
            case 2008: return "White LS"
            case 2009: return "Green Striped LS"
            case 2010: return "Squidmark LS"
            case 2011: return "Zink LS"
            case 2012: return "Striped Peaks LS"
            case 3000: return "White Layered LS"
            case 3001: return "Yellow Layered LS"
            case 3002: return "Camo Layered LS"
            case 3003: return "Black Layered LS"
            case 3004: return "Zink Layered LS"
            case 3005: return "Layered Anchor LS"
            case 3006: return "Choco Layered LS"
            case 3007: return "Part-Time Pirate"
            case 3008: return "Layered Vector LS"
            case 3009: return "Green Tee"
            case 4000: return "Pink Shrimp Polo"
            case 4001: return "Striped Rugby"
            case 4002: return "Tricolor Rugby"
            case 4003: return "Sage Green Polo"
            case 4004: return "Black Polo"
            case 4005: return "Cycling Shirt"
            case 4006: return "Cycle King Jersey"
            case 4007: return "Slipstream United"
            case 4008: return "FC Albacore"
            case 5000: return "Olive Ski Jacket"
            case 5002: return "Berry Ski Jacket"
            case 5003: return "Varsity Jacket"
            case 5004: return "School Jersey"
            case 5005: return "Green Cardigan"
            case 5006: return "Black Inky Rider"
            case 5007: return "White Inky Rider"
            case 5008: return "Retro Gamer Jersey"
            case 5009: return "Orange Cardigan"
            case 5010: return "Forge Inkling Perka"
            case 5011: return "Forge Octarian Jacket"
            case 5012: return "Blue Sailor Suit"
            case 5013: return "White Sailor Suit"
            case 5014: return "Squid Satin Jacket"
            case 5015: return "Zapfish Satin Jacket"
            case 5016: return "Krak-On 528"
            case 6000: return "B-ball Jersey (Home)"
            case 6001: return "B-ball Jersey (Away)"
            case 6002: return "SQUID GIRL Tunic"
            case 7000: return "Gray College Sweat"
            case 7001: return "Squidmark Sweat"
            case 7002: return "Retro Sweat"
            case 7003: return "Firefin Navy Sweat"
            case 7004: return "Navy College Sweat"
            case 7005: return "Reel Sweat"
            case 7006: return "Anchor Sweat"
            case 8000: return "Lumberjack Shirt"
            case 8001: return "Rodeo Shirt"
            case 8002: return "Green Check Shirt"
            case 8003: return "White Shirt"
            case 8004: return "Urchins Jersey"
            case 8005: return "Aloha Shirt"
            case 8006: return "Red Check Shirt"
            case 8007: return "Baby Jelly Shirt"
            case 8008: return "Baseball Jersey"
            case 8009: return "Gray Mixed Shirt"
            case 8010: return "Vintage Check Shirt"
            case 8011: return "Round Collar Shirt"
            case 8012: return "Logo Aloha Shirt"
            case 8013: return "Striped Shirt"
            case 8014: return "Linen Shirt"
            case 8015: return "Shirt & Tie"
            case 8016: return "Traditional Apron"
            case 9000: return "Mountain Vest"
            case 9001: return "Forest Vest"
            case 9002: return "Dark Urban Vest"
            case 9003: return "Yellow Urban Vest"
            case 9004: return "Squid-Pattern Waistcoat"
            case 9005: return "Squidstar Waistcoat"
            case 10000: return "Camo Zip Hoodie"
            case 10001: return "Green Zip Hoodie"
            case 10002: return "Zekko Hoodie"
            case 10003: return "CoroCoro Hoodie"
            case 25000: return "School Uniform"
            case 25001: return "Samurai Jacket"
            case 25002: return "Power Armor"
            case 26000: return "Splatfest Tee"
            case 26001: return "?HAP001_A"
            case 26002: return "?HAP001_B"
            case 26033: return "?HAP1001_A"
            case 26034: return "?HAP1001_B"
            case 26035: return "?HAP2001_A"
            case 26036: return "?HAP2001_B"
            case 26037: return "?HAP3001_A"
            case 26038: return "?HAP3001_B"
            case 26039: return "?HAP1002_A"
            case 26040: return "?HAP1002_B"
            case 26041: return "?HAP2002_A"
            case 26042: return "?HAP2002_B"
            case 26043: return "?HAP3002_A"
            case 26044: return "?HAP3002_B"
            case 26045: return "?HAP1003_A"
            case 26046: return "?HAP1003_B"
            case 26047: return "?HAP2003_A"
            case 26048: return "?HAP2003_B"
            case 26049: return "?HAP3003_A"
            case 26050: return "?HAP3003_B"
            case 26051: return "?HAP1012_A"
            case 26052: return "?HAP1012_B"
            case 26053: return "?HAP2004_A"
            case 26054: return "?HAP2004_B"
            case 26055: return "?HAP3004_A"
            case 26056: return "?HAP3004_B"
            case 26057: return "?HAP1005_A"
            case 26058: return "?HAP1005_B"
            case 26059: return "?HAP2005_A"
            case 26060: return "?HAP2005_B"
            case 26061: return "?HAP1007_A"
            case 26062: return "?HAP1007_B"
            case 26063: return "?HAP2006_A"
            case 26064: return "?HAP2006_B"
            case 26065: return "?HAP1008_A"
            case 26066: return "?HAP1008_B"
            case 26067: return "?HAP2007_A"
            case 26068: return "?HAP2007_B"
            case 26069: return "?HAP3007_A"
            case 26070: return "?HAP3007_B"
            case 26071: return "?HAP1009_A"
            case 26072: return "?HAP1009_B"
            case 26073: return "?HAP2008_A"
            case 26074: return "?HAP2008_B"
            case 26075: return "?HAP3008_A"
            case 26076: return "?HAP3008_B"
            case 26077: return "?HAP1015_A"
            case 26078: return "?HAP1015_B"
            case 26079: return "?HAP2009_A"
            case 26080: return "?HAP2009_B"
            case 26081: return "?HAP3009_A"
            case 26082: return "?HAP3009_B"
            case 26083: return "?HAP3010_A"
            case 26084: return "?HAP3010_B"
            case 26085: return "?HAP1011_A"
            case 26086: return "?HAP1011_B"
            case 26087: return "?HAP2011_A"
            case 26088: return "?HAP2011_B"
            case 26089: return "?HAP3011_A"
            case 26090: return "?HAP3011_B"
            case 26091: return "?HAP3012_A"
            case 26092: return "?HAP3012_B"
            case 26093: return "?HAP1013_A"
            case 26094: return "?HAP1013_B"
            case 26095: return "?HAP3013_A"
            case 26096: return "?HAP3013_B"
            case 26097: return "?HAP1017_A"
            case 26098: return "?HAP1017_B"
            case 26099: return "?HAP1018_A"
            case 26100: return "?HAP1018_B"
            case 26101: return "?HAP3014_A"
            case 26102: return "?HAP3014_B"
            case 26103: return "?HAP2016_A"
            case 26104: return "?HAP2016_B"
            case 26105: return "?HAP3019_A"
            case 26106: return "?HAP3019_B"
            case 26107: return "?HAP2019_A"
            case 26108: return "?HAP2019_B"
            case 26109: return "?HAP1021_A"
            case 26110: return "?HAP1021_B"
            case 26111: return "?HAP2020_A"
            case 26112: return "?HAP2020_B"
            case 26113: return "?HAP3020_A"
            case 26114: return "?HAP3020_B"
            case 26115: return "?HAP3021_A"
            case 26116: return "?HAP3021_B"
            case 26117: return "?HAP1022_A"
            case 26118: return "?HAP1022_B"
            case 26119: return "?HAP1023_A"
            case 26120: return "?HAP1023_B"
            case 26121: return "?HAP3022_A"
            case 26122: return "?HAP3022_B"
            case 26123: return "?HAP3023_A"
            case 26124: return "?HAP3023_B"
            case 26125: return "?HAP1024_A"
            case 26126: return "?HAP1024_B"
            case 26127: return "?HAP1025_A"
            case 26128: return "?HAP1025_B"
            case 26129: return "?HAP1020_A"
            case 26130: return "?HAP1020_B"
            case 26131: return "?HAP1026_A"
            case 26132: return "?HAP1026_B"
            case 26133: return "?HAP3024_A"
            case 26134: return "?HAP3024_B"
            case 26135: return "?HAP2021_A"
            case 26136: return "?HAP2021_B"
            case 27000: return "Hero Jacket Replica"
            case 27001: return "?MSN001"
            case 27002: return "?MSN002"
            case 27003: return "?MSN003"
            case 27004: return "Armor Jacket Replica"
            case 28000: return "Octoling Armor"
            case 29000: return "Attack_Up"
            case 29001: return "Defense_Up"
            case 29002: return "MainInk_Save"
            case 29003: return "SubInk_Save"
            case 29004: return "InkRecovery_Up"
            case 29005: return "HumanMove_Up"
            case 29006: return "SquidMove_Up"
            case 29007: return "SpecialIncrease_Up"
            case 29008: return "SpecialTime_Up"
            case 29009: return "RespawnTime_Save"
            case 29010: return "RespawnSpecialGauge_Save"
            case 29011: return "JumpTime_Save"
            case 29012: return "BombDistance_Up"
            case 29013: return "MarkingCancel"
            case 29014: return "SquidMoveSpatter_Reduction"
            case 29015: return "DeathMarking"
            case 29016: return "RespawnRadar"
            case 29500: return "?SUP000"
            case 29501: return "?SUP001"
            case _: return "Unknown"

    def get_headgear(self):
        match self.headgear:
            case 0: return "ARINOMAMA"
            case 1: return "White Headband"
            case 1000: return "Urchins Cap"
            case 1001: return "Lightweight Cap"
            case 1002: return "Takoroka Mesh"
            case 1003: return "Streetstyle Cap"
            case 1004: return "Squid-Stitch Cap"
            case 1005: return "Squidvader Cap"
            case 1006: return "Camo Mesh Cap"
            case 1007: return "Five-Panel Cap"
            case 1008: return "Zekko Mesh"
            case 1009: return "Backwards Cap"
            case 1010: return "Two-Stripe Mesh Cap"
            case 1011: return "Jet Cap"
            case 1012: return "Cycling Cap"
            case 1013: return "SQUID GIRL Hat"
            case 1014: return "Cycle King Cap"
            case 1015: return "Legendary Cap"
            case 1016: return "CoroCoro Cap"
            case 2000: return "Bobble Hat"
            case 2001: return "Short Beanie"
            case 2002: return "Striped Beanie"
            case 2003: return "Sporty Bobble Hat"
            case 2004: return "Special Forces Beret"
            case 2005: return "Squid Nordic"
            case 3000: return "Retro Specs"
            case 3001: return "Splash Googles"
            case 3002: return "Pilot Goggles"
            case 3003: return "Tinted Shades"
            case 3004: return "Black Arrowbands"
            case 3005: return "Snorkel Mask"
            case 3006: return "White Arrowbands"
            case 3007: return "Fake Contacts"
            case 3008: return "18K Aviators"
            case 3009: return "Full Moon Glasses"
            case 3010: return "Octoglasses"
            case 4000: return "Jungle Hat"
            case 4001: return "Safari Hat"
            case 4002: return "Camping Hat"
            case 4003: return "Blowfish Bell Hat"
            case 4004: return "Bamboo Hat"
            case 4005: return "Straw Boater"
            case 4006: return "Classic Straw Boater"
            case 4007: return "Treasure Hunter"
            case 5000: return "Studio Headphones"
            case 5001: return "Designer Headphones"
            case 5002: return "Noise Cancelers"
            case 6000: return "Golf Visor"
            case 6001: return "FishFry Visor"
            case 6002: return "Sun Visor"
            case 7000: return "Cycle Helmet"
            case 7002: return "Stealth Goggles"
            case 7003: return "Tentacles Helmet"
            case 7004: return "Skate Helmet"
            case 7005: return "Visor Skate Helmet"
            case 8000: return "Gas Mask"
            case 8001: return "Paintball Mask"
            case 8002: return "Paisley Bandana"
            case 8003: return "Skull Bandana"
            case 9001: return "B-ball Headband"
            case 9002: return "Squash Headband"
            case 9003: return "Tennis Headband"
            case 9004: return "Jogging Headband"
            case 9005: return "Soccer Headband"
            case 9006: return "Traditional Headband"
            case 25000: return "Squid Hairclip"
            case 25001: return "Samurai Helmet"
            case 25002: return "Power Mask"
            case 27000: return "Hero Headset Replica"
            case 27001: return "?MSN001"
            case 27002: return "?MSN002"
            case 27003: return "?MSN003"
            case 27004: return "?MSN004"
            case 28000: return "Octoling Goggles"
            case 28001: return "ヘルメットライバル用強"
            case 29000: return "Attack_Up"
            case 29001: return "Defense_Up"
            case 29002: return "MainInk_Save"
            case 29003: return "?SubInk_Save"
            case 29004: return "?InkRecovery_Up"
            case 29005: return "?HumanMove_Up"
            case 29006: return "?SquidMove_Up"
            case 29007: return "?SpecialIncrease_Up"
            case 29008: return "?SpecialTime_Up"
            case 29009: return "?RespawnTime_Save"
            case 29010: return "?RespawnSpecialGauge_Save"
            case 29011: return "?JumpTime_Save"
            case 29012: return "?BombDistance_Up"
            case 29013: return "?StartAllUp"
            case 29014: return "?EndAllUp"
            case 29015: return "?MinorityUp"
            case 29016: return "?ComeBack"
            case 29500: return "?SUP000"
            case 29501: return "?SUP001"
            case _: return "Unknown"

    def get_rank(self):
        match self.rank:
            case 0: return "C-"
            case 1: return "C"
            case 2: return "C+"
            case 3: return "B-"
            case 4: return "B"
            case 5: return "B+"
            case 6: return "A-"
            case 7: return "A"
            case 8: return "A+"
            case 9: return "S"
            case 10: return "S+"
            case _: return "Unknown"

    def get_weapon(self):
        match self.weapon:
            case 100: return "Sploosh-o-matic"
            case 101: return "Neo Sploosh-o-matic"
            case 102: return "Splattershot Jr."
            case 103: return "Custom Splattershot Jr."
            case 104: return "Splash-o-matic"
            case 105: return "Neo Splash-o-matic"
            case 106: return "Aerospray MG"
            case 107: return "Aerospray RG"
            case 108: return "Splattershot"
            case 109: return "Tentatek Splattershot"
            case 110: return "Hero Shot Replica"
            case 111: return "Octoshot Replica"
            case 112: return ".52 Gal"
            case 113: return ".52 Gal Deco"
            case 114: return "N-ZAP '85"
            case 115: return "N-ZAP '89"
            case 116: return "Splattershot Pro"
            case 117: return "Forge Splattershot Pro"
            case 118: return ".96 Gal"
            case 119: return ".96 Gal Deco"
            case 120: return "Dual Squelcher"
            case 121: return "Custom Dual Squelcher"
            case 122: return "Jet Squelcher"
            case 123: return "Custom Jet Squelcher"
            case 124: return "Luna Blaster"
            case 125: return "Luna Blaster Neo"
            case 126: return "Blaster"
            case 127: return "Custom Blaster"
            case 128: return "Range Blaster"
            case 129: return "Custom Range Blaster"
            case 130: return "Rapid Blaster"
            case 131: return "Rapid Blaster Deco"
            case 132: return "Rapid Blaster Pro"
            case 133: return "Rapid Blaster Pro Deco"
            case 134: return "L-3 Nozzlenose"
            case 135: return "L-3 Nozzlenose D"
            case 136: return "H-3 Nozzlenose"
            case 137: return "H-3 Nozzlenose D"
            case 138: return "Wasabi Splattershot"
            case 139: return "Berry Splattershot Pro"
            case 140: return "Sploosh-o-matic 7"
            case 141: return "Aerospray PG"
            case 142: return "N-ZAP '83"
            case 143: return "Grim Range Blaster"
            case 144: return "Cherry H-3 Nozzlenose"
            case 200: return "Carbon Roller"
            case 201: return "Carbon Roller Deco"
            case 202: return "Splat Roller"
            case 203: return "Krak-On Splat Roller"
            case 204: return "Hero Roller Replica"
            case 205: return "Dynamo Roller"
            case 206: return "Gold Dynamo Roller"
            case 207: return "Inkbrush"
            case 208: return "Inkbrush Nouveau"
            case 209: return "Octobrush"
            case 210: return "Octobrush Nouveau"
            case 211: return "Tempered Dynamo Roller"
            case 212: return "Permanent Inkbrush"
            case 213: return "CoroCoro Splat Roller"
            case 300: return "Classic Squiffer"
            case 301: return "New Squiffer"
            case 302: return "Splat Charger"
            case 303: return "Kelp Splat Charger"
            case 304: return "Hero Charger Replica"
            case 305: return "Splatterscope"
            case 306: return "Kelp Splatterscope"
            case 307: return "E-liter 3K"
            case 308: return "Custom E-liter 3K"
            case 309: return "E-liter 3K Scope"
            case 310: return "Custom E-liter 3K Scope"
            case 311: return "Bamboozler 14 Mk I"
            case 312: return "Bamboozler 14 Mk II"
            case 313: return "Fresh Squiffer"
            case 314: return "Bamboozler 14 Mk III"
            case 315: return "Bento Splat Charger"
            case 316: return "Bento Splatterscope"
            case 400: return "Slosher"
            case 401: return "Slosher Deco"
            case 402: return "Tri-Slosher"
            case 403: return "Tri-Slosher Nouveau"
            case 404: return "Sloshing Machine"
            case 405: return "Sloshing Machine Neo"
            case 406: return "Soda Slosher"
            case 500: return "Mini Splatling"
            case 501: return "Zink Mini Splatling "
            case 502: return "Heavy Splatling"
            case 503: return "Heavy Splatling Deco"
            case 504: return "Hydra Splatling"
            case 505: return "Custom Hydra Splatling"
            case 506: return "Refurbished Mini Splatling"
            case 507: return "Heavy Splatling Remix"
            case 1000: return "?Shot_Msn0Lv0"
            case 1001: return "?Shot_Msn0Lv1"
            case 1002: return "?Shot_Msn0Lv2"
            case 1003: return "?Shot_Msn0Lv3"
            case 1100: return "?Roller_Mission"
            case 1200: return "?Charge_Mission"
            case 1800: return "?BigBall_SpecAdjust01"
            case 1801: return "?BigBall_SpecAdjust02"
            case 2000: return "?Shot_Rvl0Lv0"
            case 2001: return "?Shot_Rvl0Lv1"
            case 2002: return "?Shot_Rvl0Lv2"
            case 2003: return "?Shot_Rvl0Lv3"
            case 5000: return "?Roller_KingSquid"
            case _: return "Unknown"

    def get_sub_weapon(self):
        match self.sub_weapon:
            case 0: return "Splat Bomb"
            case 1: return "Suction Bomb"
            case 2: return "Burst Bomb"
            case 3: return "Seeker"
            case 4: return "Point Sensor"
            case 5: return "Ink Mine"
            case 6: return "Sprinkler"
            case 7: return "Squid Beakon"
            case 8: return "Splash Wall"
            case 9: return "Disruptor"
            case 1000: return "?Bomb_Msn0Lv0"
            case 1001: return "?Bomb_Msn0Lv1"
            case 1002: return "?Bomb_Msn0Lv2"
            case 1003: return "?Bomb_Msn0Lv3"
            case 1100: return "?Bomb_Msn1Lv0"
            case 1101: return "?Bomb_Msn1Lv1"
            case 1102: return "?Bomb_Msn1Lv2"
            case 1103: return "?Bomb_Msn1Lv3"
            case 1200: return "?Bomb_Msn2Lv0"
            case 1201: return "?Bomb_Msn2Lv1"
            case 1202: return "?Bomb_Msn2Lv2"
            case 1203: return "?Bomb_Msn2Lv3"
            case 2000: return "?Bomb_Rvl0Lv0"
            case 2001: return "?Bomb_Rvl0Lv1"
            case 2002: return "?Bomb_Rvl0Lv2"
            case 2003: return "?Bomb_Rvl0Lv3"
            case _: return "Unknown"

    def get_special_weapon(self):
        match self.special_weapon:
            case 0: return "Inkzooka"
            case 1: return "Killer Wail"
            case 2: return "Inkstrike"
            case 3: return "Bubbler"
            case 4: return "Bomb Rush"
            case 5: return "Kraken"
            case 6: return "Echolocator"
            case 7: return "Rainmaker"
            case _: return "Unknown"
